# Generated by Django 2.1.1 on 2019-01-28 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('limit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryRecordApi',
            fields=[
                ('recordid', models.AutoField(primary_key=True, serialize=False)),
                ('dietarydate', models.DateField()),
                ('dietarytime', models.CharField(max_length=50)),
                ('share', models.FloatField(null=True)),
                ('calories', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'dietaryrecordsapi',
            },
        ),
        migrations.CreateModel(
            name='FoodCategoryApi',
            fields=[
                ('foodcategoryid', models.AutoField(primary_key=True, serialize=False)),
                ('foodcategory', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'foodcategorysapi',
            },
        ),
        migrations.CreateModel(
            name='FoodListApi',
            fields=[
                ('foodid', models.AutoField(primary_key=True, serialize=False)),
                ('foodname', models.CharField(max_length=50)),
                ('foodcalories', models.FloatField(null=True)),
                ('foodprotein', models.FloatField(null=True)),
                ('foodfat', models.FloatField(null=True)),
                ('foodfarbohydrate', models.FloatField(null=True)),
                ('fooddescription', models.CharField(max_length=500, null=True)),
                ('foodcategoryid', models.ForeignKey(db_column='foodcategoryid', on_delete=django.db.models.deletion.DO_NOTHING, to='foodrestful.FoodCategoryApi')),
                ('userid', models.ForeignKey(db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='limit.User')),
            ],
            options={
                'db_table': 'footlistsapi',
            },
        ),
        migrations.AddField(
            model_name='dietaryrecordapi',
            name='foodid',
            field=models.ForeignKey(db_column='foodid', on_delete=django.db.models.deletion.DO_NOTHING, to='foodrestful.FoodListApi'),
        ),
        migrations.AddField(
            model_name='dietaryrecordapi',
            name='userid',
            field=models.ForeignKey(db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='limit.User'),
        ),
    ]
