# Generated by Django 2.1.1 on 2018-10-11 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('limit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='運動項目')),
                ('cal', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='卡洛里(每小時/每公斤)')),
                ('mdate', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('state', models.BooleanField(verbose_name='狀態(1:啟用/0:停用)')),
                ('cdate', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='limit.User', verbose_name='建立人員')),
            ],
            options={
                'db_table': 'sport_sportitem',
            },
        ),
        migrations.CreateModel(
            name='SportRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdate', models.DateField(verbose_name='運動日期')),
                ('duration', models.IntegerField(verbose_name='運動持續時間(分鐘)')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='體重')),
                ('cal', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='運動消耗卡洛里calorie')),
                ('mdate', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('cdate', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
                ('cuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='limit.User', verbose_name='建立人員')),
                ('sportid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sport.SportItem', verbose_name='運動項目')),
            ],
            options={
                'db_table': 'sport_sportrecord',
            },
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='體重(公斤)')),
                ('cdate', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
                ('mdate', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='limit.User', verbose_name='建立人員')),
            ],
            options={
                'db_table': 'sport_weightrecord',
            },
        ),
    ]
