# Generated by Django 2.1.1 on 2019-01-28 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('on_account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='On_Account',
        ),
    ]
